### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by headius** [deepfryed/idn-ruby#2]
Hello!

I ran into this library while trying to install dependencies for Mastodon. I want JRuby support! 😁 

The C code is obviously not very big. Could it be FFI? It appears to depend on idn as an external library already.

The other option might be if there's some equivalent library on the JVM we could wrap. There would be no external deps then.

In any case, it shouldn't be too hard to add JRuby support, and we want to help!

**Comment by deepfryed** [comment]
anything for you sir, I'll take a look tonight.

**Comment by jeremyhaile** [comment]
@deepfryed any update on this? I'm also trying to get it running in JRuby. Appreciate it!

**Comment by oshanz** [comment]
I'm also trying to run Mastodon on JRuby. any updates? :smiley:

**Comment by headius** [comment]
FWIW, sassc is an example of an FFI-based gem that ships the C code it binds and builds that code as if it were an extension. It works fine on JRuby, because it just compiles the code into a dynamic library we can load from Ruby.

**Comment by deepfryed** [comment]
sorry haven't had the time to look into porting everything over to FFI, if someone can send a PR that'd be much appreciated.
